version: "3.0"
services:
  mysql:
    image: mariadb:10.5.8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=no-secret
      - MYSQL_DATABASE=tab_author
    volumes:
      - "./docker/mysql/scripts:/docker-entrypoint-initdb.d"

  esc:
    image: elasticsearch:7.16.3
    environment:
      - node.name=esc
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=esc
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  nginx:
    build: ./docker/nginx
    volumes:
      - "./docker/nginx/log:/var/log/nginx"
      - "./docker/nginx/cache:/opt/vwtab/proxy_cache"
      - "./docker/nginx/socialmedia:/opt/vwtab/socialmedia"
      - "./docker/nginx/apidoc:/opt/vwtab/apidoc"
      - "./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  #  mgnl_public:
  #    build: ./docker/mgnl_public
  #    ports:
  #      - "8181:8080"
  #    volumes:
  #      - "./hibiscus/hibiscus-ui/target/magnolia-resources:/hibiscus"
  #      - "./magnolia/vw-tab-website-webapp/repositories/public:/repository"
  #      - "./docker/mgnl_public:/webapp"
  #    depends_on:
  #      - "mysql"
  #    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 120s java -jar /webapp/public.jar

  smtpDebug:
    image: glomium/debug-smtp
    ports:
      - "25:25"
